version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type: chore"
    commit-message:
      prefix: chore

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type: chore"
    commit-message:
      prefix: chore
